# Theme
remote_theme: metacubed/metacubed.github.io@theme

# Title and tag line
title: 'metacubed'
description: 'Pushkaraj Shirgaonkar'

# Images
background: 'background.jpg'
avatar: 'https://avatars.githubusercontent.com/u/7028125'
favicon: 'https://avatars.githubusercontent.com/u/7028125?s=32'

# Online profiles
'Stack Overflow': '2702368'
'GitHub': 'metacubed'
'Blog': '/'
'LinkedIn': 'shirgaonkar'

social-links-order: ['Stack Overflow', 'GitHub', 'Blog', 'LinkedIn']

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**

social-links:

  - name: 'Stack Overflow'
    url-pattern: stackoverflow.com/users/__USERNAME__
    icon-class: fab fa-2x fa-stack-overflow

  - name: 'GitHub'
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: 'Blog'
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-feather

  - name: 'LinkedIn'
    url-pattern: linkedin.com/in/__USERNAME__
    icon-class: fab fa-2x fa-linkedin-in

  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: twitter
    url-pattern: twitter.com/__USERNAME__

  - name: google-plus
    url-pattern: plus.google.com/+__USERNAME__

  - name: vk
    url-pattern: vk.com/__USERNAME__

  - name: weibo
    url-pattern: weibo.com/__USERNAME__

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: flickr
    url-pattern: flickr.com/__USERNAME__

  - name: pinterest
    url-pattern: pinterest.com/__USERNAME__

  - name: gitlab
    url-pattern: gitlab.com/__USERNAME__
    icon-class: fab fa-2x fa-gitlab

  - name: codepen
    url-pattern: codepen.com/__USERNAME__

  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__

  - name: rubygems
    url-pattern: rubygems.org/profiles/__USERNAME__
    icon-class: far fa-2x fa-gem

  - name: steam
    url-pattern: steamcommunity.com/id/__USERNAME__

  - name: youtube
    url-pattern: youtube.com/__USERNAME__

  - name: vimeo
    url-pattern: vimeo.com/__USERNAME__

  - name: soundcloud
    url-pattern: soundcloud.com/__USERNAME__

  - name: lastfm
    url-pattern: last.fm/user/__USERNAME__

  - name: medium
    url-pattern: medium.com/@__USERNAME__

  - name: tumblr
    url-pattern: __USERNAME__.tumblr.com

  - name: dribbble
    url-pattern: dribbble.com/__USERNAME__

  - name: keybase
    url-pattern: keybase.io/__USERNAME__

  - name: messenger
    url-pattern: m.me/__USERNAME__
    icon-class: fab fa-2x fa-facebook-messenger

  - name: telegram
    url-pattern: telegram.me/__USERNAME__

  - name: snapchat
    url-pattern: snapchat.com/add/__USERNAME__

  - name: quora
    url-pattern: www.quora.com/profile/__USERNAME__

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open
